Unit Conversion Program

In [ ]:
def meters_to_feet(meters):
    """Convert meters to feet."""
    return meters * 3.28084

def feet_to_meters(feet):
    """Convert feet to meters."""
    return feet / 3.28084

def kilograms_to_pounds(kg):
    """Convert kilograms to pounds."""
    return kg * 2.20462

def pounds_to_kilograms(lbs):
    """Convert pounds to kilograms."""
    return lbs / 2.20462

def liters_to_gallons(liters):
    """Convert liters to gallons."""
    return liters * 0.264172

def gallons_to_liters(gallons):
    """Convert gallons to liters."""
    return gallons / 0.264172

def unit_converter():
    """Main function to handle unit conversion based on user choice."""
    print("Choose the conversion type:")
    print("1. Length (Meters <-> Feet)")
    print("2. Weight (Kilograms <-> Pounds)")
    print("3. Volume (Liters <-> Gallons)")

    try:
        choice = int(input("Enter the number of your choice: "))

        if choice == 1:
            print("1. Meters to Feet")
            print("2. Feet to Meters")
            sub_choice = int(input("Enter 1 or 2: "))

            value = float(input("Enter the value to convert: "))

            if sub_choice == 1:
                print(f"{value} meters is {meters_to_feet(value):.2f} feet")
            elif sub_choice == 2:
                print(f"{value} feet is {feet_to_meters(value):.2f} meters")
            else:
                print("Invalid choice.")

        elif choice == 2:
            print("1. Kilograms to Pounds")
            print("2. Pounds to Kilograms")
            sub_choice = int(input("Enter 1 or 2: "))

            value = float(input("Enter the value to convert: "))

            if sub_choice == 1:
                print(f"{value} kg is {kilograms_to_pounds(value):.2f} lbs")
            elif sub_choice == 2:
                print(f"{value} lbs is {pounds_to_kilograms(value):.2f} kg")
            else:
                print("Invalid choice.")

        elif choice == 3:
            print("1. Liters to Gallons")
            print("2. Gallons to Liters")
            sub_choice = int(input("Enter 1 or 2: "))

            value = float(input("Enter the value to convert: "))

            if sub_choice == 1:
                print(f"{value} liters is {liters_to_gallons(value):.2f} gallons")
            elif sub_choice == 2:
                print(f"{value} gallons is {gallons_to_liters(value):.2f} liters")
            else:
                print("Invalid choice.")

        else:
            print("Invalid choice. Please select 1, 2, or 3.")

    except ValueError:
        print("Invalid input! Please enter a number.")

# Run the function
unit_converter()


Choose the conversion type:
1. Length (Meters <-> Feet)
2. Weight (Kilograms <-> Pounds)
3. Volume (Liters <-> Gallons)
Enter the number of your choice: 2
1. Kilograms to Pounds
2. Pounds to Kilograms
Enter 1 or 2: 1
Enter the value to convert: 33
33.0 kg is 72.75 lbs


 Mathematical Operations on a List of Numbers

In [ ]:
def calculate_sum(numbers):
    """Returns the sum of a list of numbers."""
    return sum(numbers)

def calculate_average(numbers):
    """Returns the average of a list of numbers."""
    return sum(numbers) / len(numbers) if numbers else 0  # Avoid division by zero

def find_maximum(numbers):
    """Returns the maximum number from the list."""
    return max(numbers) if numbers else None

def find_minimum(numbers):
    """Returns the minimum number from the list."""
    return min(numbers) if numbers else None
def math_operations():
    """Main function to handle mathematical operations on a list of numbers."""
    print("Choose an operation:")
    print("1. Sum of numbers")
    print("2. Average of numbers")
    print("3. Maximum number")
    print("4. Minimum number")

    try:
        choice = int(input("Enter the number of your choice: "))

        numbers = input("Enter a list of numbers separated by spaces: ").split()
        numbers = [float(num) for num in numbers]  # Convert input to float list

        if not numbers:
            print("The list is empty! Please enter valid numbers.")
            return

        if choice == 1:
            print(f"The sum is: {calculate_sum(numbers)}")
        elif choice == 2:
            print(f"The average is: {calculate_average(numbers):.2f}")
        elif choice == 3:
            print(f"The maximum number is: {find_maximum(numbers)}")
        elif choice == 4:
            print(f"The minimum number is: {find_minimum(numbers)}")
        else:
            print("Invalid choice! Please select 1, 2, 3, or 4.")

    except ValueError:
        print("Invalid input! Please enter numbers only.")

# Run the function
math_operations()


Choose an operation:
1. Sum of numbers
2. Average of numbers
3. Maximum number
4. Minimum number
Enter the number of your choice: 4
Enter a list of numbers separated by spaces: 11 33 4
The minimum number is: 4.0


4.2 Exercise on List Manipulation
Extract Every Other Element


In [ ]:
def extract_every_other(lst):
    """Returns a new list containing every other element from the input list."""
    return lst[::2]

# Example usage
numbers = [1, 2, 3, 4, 5, 6]
print(extract_every_other(numbers))


[1, 3, 5]


Slice a Sublist

In [ ]:
def get_sublist(lst, start, end):
    """Returns a sublist from start to end (inclusive)."""
    return lst[start:end+1]  # +1 to include end index

# Example usage
numbers = [1, 2, 3, 4, 5, 6]
print(get_sublist(numbers, 2, 4))


[3, 4, 5]


Reverse a List Using Slicing

In [ ]:
def reverse_list(lst):
    """Returns a reversed list using slicing."""
    return lst[::-1]

# Example usage
numbers = [1, 2, 3, 4, 5]
print(reverse_list(numbers))


[5, 4, 3, 2, 1]


Remove the First and Last Elements

In [ ]:
def remove_first_last(lst):
    """Removes the first and last elements from the list."""
    return lst[1:-1]

# Example usage
numbers = [1, 2, 3, 4, 5]
print(remove_first_last(numbers))


[2, 3, 4]


Get the First n Elements

In [ ]:
def get_first_n(lst, n):
    """Returns the first n elements of the list."""
    return lst[:n]

# Example usage
numbers = [1, 2, 3, 4, 5]
print(get_first_n(numbers, 3))


[1, 2, 3]


Extract Elements from the End

In [ ]:
def get_last_n(lst, n):
    """Returns the last n elements of the list."""
    return lst[-n:]

# Example usage
numbers = [1, 2, 3, 4, 5]
print(get_last_n(numbers, 2))


[4, 5]


Extract Elements in Reverse Order

In [ ]:
def reverse_skip(lst):
    """Returns every second element in reverse order starting from the second-to-last element."""
    return lst[-2::-2]

# Example usage
numbers = [1, 2, 3, 4, 5, 6]
print(reverse_skip(numbers))


[5, 3, 1]


1. Flatten a Nested List:
 Write a Python function that takes a nested list and flattens it into a single list, where all the elements
 are in a single dimension.

In [ ]:
def flatten(lst):
    """Flattens a nested list into a single list."""
    flat_list = []
    for sublist in lst:
        if isinstance(sublist, list):  # Check if the element is a list
            flat_list.extend(flatten(sublist))  # Recursively flatten
        else:
            flat_list.append(sublist)
    return flat_list

# Example usage
nested_list = [[1, 2], [3, 4], [5]]
print(flatten(nested_list))


[1, 2, 3, 4, 5]


 2. Accessing Nested List Elements:
 Write a Python function that extracts a specific element from a nested list given its indices.

In [ ]:
def access_nested_element(lst, indices):
    """Returns the element at the given indices in a nested list."""
    element = lst
    for index in indices:
        element = element[index]
    return element

# Example usage
nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(access_nested_element(nested_list, [1, 2]))

6


3. Sum of All Elements in a Nested List:
 Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

In [ ]:
def sum_nested(lst):
    """Returns the sum of all numbers in a nested list."""
    return sum(flatten(lst))  # Use flatten function from earlier

# Example usage
nested_list = [[1, 2], [3, [4, 5]], 6]
print(sum_nested(nested_list))


21


4. Remove Specific Element from a Nested List:
 Write a Python function that removes all occurrences of a specific element from a nested list.

In [ ]:
def remove_element(lst, elem):
    """Removes all occurrences of a specific element from a nested list."""
    if isinstance(lst, list):
        return [remove_element(x, elem) for x in lst if x != elem]
    return lst

# Example usage
nested_list = [[1, 2], [3, 2], [4, 5]]
print(remove_element(nested_list, 2))


[[1], [3], [4, 5]]


 5. Find the Maximum Element in a Nested List:
 Write a Python function that finds the maximum element in a nested list (regardless of depth).

In [ ]:
def find_max(lst):
    """Returns the maximum element in a nested list."""
    return max(flatten(lst))  # Use flatten function


nested_list = [[1, 2], [3, [4, 5]], 6]
print(find_max(nested_list))


6


 6. Count Occurrences of an Element in a Nested List:
 Write a Python function that counts how many times a specific element appears in a nested list.

In [ ]:
def count_occurrences(lst, elem):
    """Counts occurrences of an element in a nested list."""
    return flatten(lst).count(elem)  # Use flatten function


nested_list = [[1, 2], [2, 3], [2, 4]]
print(count_occurrences(nested_list, 2))


3


7. Flatten a List of Lists of Lists:
 Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

In [ ]:
def deep_flatten(lst):
    """Flattens a deeply nested list into a single list."""
    return flatten(lst)  # Use the same flatten function


nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
print(deep_flatten(nested_list))


[1, 2, 3, 4, 5, 6, 7, 8]


 8. Nested List Average:
 Write a Python function that calculates the average of all elements in a nested list.

In [ ]:
def average_nested(lst):
    """Returns the average of all numbers in a nested list."""
    flat_list = flatten(lst)
    return sum(flat_list) / len(flat_list) if flat_list else 0


nested_list = [[1, 2], [3, 4], [5, 6]]
print(average_nested(nested_list))


3.5


To- Do- NumPy
 Basic Vector and Matrix Operation with Numpy.

 Problem- 1: Array Creation:
 Complete the following Tasks:
 1. Initialize an empty array with size 2X2.
 2. Initialize an all one array with size 4X2.
 3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
 4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
 5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
 6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np
empty_array = np.empty((2, 2))
print("Empty Array:\n", empty_array)

ones_array = np.ones((4, 2))
print("All Ones Array:\n", ones_array)

filled_array = np.full((3, 3), 7)  # Example fill value of 7
print("Filled Array:\n", filled_array)

reference_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_array = np.zeros_like(reference_array)
print("Zeros Like Array:\n", zeros_like_array)

ones_like_array = np.ones_like(reference_array)
print("Ones Like Array:\n", ones_like_array)

new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("Numpy Array from List:\n", numpy_array)

Empty Array:
 [[2.0291767e-316 0.0000000e+000]
 [1.3351129e-306 2.2727020e-322]]
All Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Filled Array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
Zeros Like Array:
 [[0 0 0]
 [0 0 0]]
Ones Like Array:
 [[1 1 1]
 [1 1 1]]
Numpy Array from List:
 [1 2 3 4]


 Problem- 2: Array Manipulation: Numerical Ranges and Array indexing:
 Complete the following tasks:
 1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
 2. Create a 3X3 matrix with values ranging from 0 to 8.
 {Hint:look for np.reshape()}
 3. Create a 3X3 identity matrix.{Hint:np.eye()}
 4. Create a random array of size 30 and find the mean of the array.
 {Hint:check for np.random.random() and array.mean() function}
 5. Create a 10X10 array with random values and find the minimum and maximum values.
 6. Create a zero array of size 10 and replace 5th element with 1.
 7. Reverse an array arr = [1,2,0,0,4,0].
 8. Create a 2d array with 1 on border and 0 inside.
 9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
array_range = np.arange(10, 50)
print("Array from 10 to 49:\n", array_range)


Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
matrix_3x3 = np.arange(9).reshape(3, 3)
print("3x3 Matrix:\n", matrix_3x3)

3x3 Matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
identity_matrix = np.eye(3)
print("3x3 Identity Matrix:\n", identity_matrix)

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
random_array = np.random.random(30)
mean_value = random_array.mean()
print("Random Array Mean:\n", mean_value)

Random Array Mean:
 0.4927701297949021


In [ ]:
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("Random 10x10 Array:")
print(random_10x10)
print("10x10 Random Array Min:", min_value)
print("10x10 Random Array Max:", max_value)

Random 10x10 Array:
[[0.17530903 0.74274105 0.93757952 0.42132681 0.21507895 0.77372893
  0.85219665 0.58590268 0.12473504 0.25363509]
 [0.75620711 0.20974255 0.07766223 0.98493893 0.35644009 0.71026684
  0.97414416 0.40565576 0.80002264 0.33575569]
 [0.33973073 0.5047246  0.70683313 0.64387888 0.27932814 0.00403978
  0.28114806 0.34704842 0.12903729 0.61944637]
 [0.91408706 0.87092037 0.33235343 0.89083362 0.62452791 0.79555711
  0.17480809 0.74048401 0.15576453 0.88735703]
 [0.50840028 0.67976037 0.78562987 0.95802968 0.14371157 0.53246806
  0.04135459 0.52315935 0.72363825 0.4438687 ]
 [0.64804064 0.58094752 0.62645437 0.94358787 0.78932736 0.56567938
  0.7518714  0.39222494 0.0456429  0.63367477]
 [0.00244679 0.34284492 0.34776709 0.22427063 0.27419392 0.73811654
  0.36563211 0.59224442 0.77005326 0.39083358]
 [0.18682512 0.68318206 0.73342959 0.54464919 0.73507141 0.19127193
  0.36687135 0.98057223 0.82122526 0.05569119]
 [0.34042958 0.73559681 0.52244592 0.15434513 0.77921902 0.7

In [ ]:
zero_array = np.zeros(10)
zero_array[4] = 1  # Replace the 5th element (index 4)
print("Zero Array with 5th Element Replaced:\n", zero_array)

Zero Array with 5th Element Replaced:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("Reversed Array:\n", reversed_arr)

Reversed Array:
 [0 4 0 0 2 1]


In [ ]:
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("2D Array with Border of 1s:\n", border_array)

2D Array with Border of 1s:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("Checkerboard Pattern:\n", checkerboard)

Checkerboard Pattern:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


 Problem- 3: Array Operations:
 For the following arrays:
 x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
 v = np.array([9,10]) and w = np.array([11,12]);
 Complete all the task using numpy:
 1. Add the two array.
 2. Subtract the two array.
 3. Multiply the array with any integers of your choice.
 4. Find the square of each element of the array.
 5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
 6. Concatenate x(and)y along row and Concatenate v(and)w along column.
 {Hint:try np.concatenate() or np.vstack() functions.
 7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

Given the arrays:

In [ ]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

In [ ]:
sum_array = x + y
print("Sum of x and y:\n", sum_array)

Sum of x and y:
 [[ 6  8]
 [10 13]]


In [ ]:
diff_array = x - y
print("Difference of x and y:\n", diff_array)

Difference of x and y:
 [[-4 -4]
 [-4 -3]]


In [ ]:
multiplied_array = x * 2
print("x multiplied by 2:\n", multiplied_array)

x multiplied by 2:
 [[ 2  4]
 [ 6 10]]


In [ ]:
squared_array = np.square(x)
print("Square of each element in x:\n", squared_array)

Square of each element in x:
 [[ 1  4]
 [ 9 25]]


In [ ]:
dot_v_w = np.dot(v, w)
dot_x_v = np.dot(x, v)
dot_x_y = np.dot(x, y)
print("Dot product of v and w:", dot_v_w)
print("Dot product of x and v:\n", dot_x_v)
print("Dot product of x and y:\n", dot_x_y)

Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]


In [ ]:
concatenated_xy = np.concatenate((x, y), axis=0)  # Along rows
concatenated_vw = np.column_stack((v, w))  # Along columns
print("Concatenated x and y along rows:\n", concatenated_xy)
print("Concatenated v and w along columns:\n", concatenated_vw)

Concatenated x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenated v and w along columns:
 [[ 9 11]
 [10 12]]


In [ ]:
try:
    concatenated_xv = np.concatenate((x, v))  # This will raise an error
except ValueError as e:
    print("Error encountered while concatenating x and v:", e)

Error encountered while concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem- 4: Matrix Operations:
 • For the following arrays:
 A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
 Prove following with Numpy:
 1. Prove A.A−1 = I.
 2. Prove AB= BA.
 3. Prove (AB)T = BTAT.
 • Solve the following system of Linear equation using Inverse Methods.
 2x −3y+z =−1
 x −y+2z =−3
 3x +y−z =9
 {Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
 • Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func
tion of Numpy

In [ ]:
# Define the matrix A
A = np.array([[3, 4], [7, 8]])

# Calculate the inverse of A
A_inv = np.linalg.inv(A)

# Multiply A by its inverse to get the identity matrix
result = np.dot(A, A_inv)

# Print the result
print("A * A^-1 = \n", result)

# Verify that the result is the identity matrix
I = np.eye(2)  # Create a 2x2 identity matrix
print("Identity matrix I = \n", I)

# Check if the result is close to the identity matrix
if np.allclose(result, I):
    print("The result is the identity matrix, so A * A^-1 = I")
else:
    print("The result is not the identity matrix")

A * A^-1 = 
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Identity matrix I = 
 [[1. 0.]
 [0. 1.]]
The result is the identity matrix, so A * A^-1 = I


In [ ]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Compute AB and BA
AB = np.dot(A, B)
BA = np.dot(B, A)

# Print the results
print("AB = \n", AB)
print("BA = \n", BA)

# Compare AB and BA
if np.array_equal(AB, BA):
    print("AB = BA")
else:
    print("AB != BA")

AB = 
 [[23 13]
 [51 29]]
BA = 
 [[36 44]
 [13 16]]
AB != BA


In [ ]:
AB_transpose = np.transpose(np.dot(A, B))

# Compute the product of the transposes B^T A^T
B_transpose_A_transpose = np.dot(np.transpose(B), np.transpose(A))

# Print both results
print("(AB)^T = \n", AB_transpose)
print("B^T A^T = \n", B_transpose_A_transpose)

# Compare (AB)^T and B^T A^T
if np.array_equal(AB_transpose, B_transpose_A_transpose):
    print("(AB)^T = B^T A^T")
else:
    print("(AB)^T != B^T A^T")

(AB)^T = 
 [[23 51]
 [13 29]]
B^T A^T = 
 [[23 51]
 [13 29]]
(AB)^T = B^T A^T


In [ ]:
import numpy as np

# Coefficient matrix A
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

# Constants matrix B
B = np.array([[-1], [-3], [9]])

# Calculate the inverse of matrix A
A_inv = np.linalg.inv(A)

# Solve for X (which contains x, y, z)
X = np.dot(A_inv, B)

# Print the solution
print("The solution is:")
print("x =", X[0][0])
print("y =", X[1][0])
print("z =", X[2][0])


The solution is:
x = 2.0
y = 1.0
z = -2.0


In [ ]:
# Coefficient matrix A
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

# Constants matrix B
B = np.array([[-1], [-3], [9]])

# Calculate the inverse of matrix A using np.linalg.inv
A_inv = np.linalg.inv(A)

# Solve for X (which contains x, y, z) using matrix multiplication
X = np.dot(A_inv, B)

# Print the solution
print("The solution is:")
print("x =", X[0][0])
print("y =", X[1][0])
print("z =", X[2][0])

The solution is:
x = 2.0
y = 1.0
z = -2.0


10.2 Experiment: How Fast is Numpy?
1. Element-wise Addition

In [ ]:
import time
import random

# Generate two lists of size 1,000,000 with random values
size = 1_000_000
list1 = [random.randint(1, 100) for _ in range(size)]
list2 = [random.randint(1, 100) for _ in range(size)]

# Measure time taken for element-wise addition using list comprehension
start_time = time.time()
result = [list1[i] + list2[i] for i in range(size)]
end_time = time.time()

# Print time taken
print(f"Time taken for element-wise addition using Python lists: {end_time - start_time:.6f} seconds")



Time taken for element-wise addition using Python lists: 0.055912 seconds


In [ ]:
import numpy as np
import time

# Generate two NumPy arrays of size 1,000,000 with random values
size = 1_000_000
array1 = np.random.randint(1, 100, size)
array2 = np.random.randint(1, 100, size)

# Measure time taken for element-wise addition using NumPy
start_time = time.time()
result = array1 + array2  # Vectorized addition
end_time = time.time()

# Print time taken
print(f"Time taken for element-wise addition using NumPy: {end_time - start_time:.6f} seconds")


Time taken for element-wise addition using NumPy: 0.013236 seconds


2. Element-wise Multiplication

In [ ]:
size = 1_000_000
list1 = [random.randint(1, 100) for _ in range(size)]
list2 = [random.randint(1, 100) for _ in range(size)]

# Measure time taken for element-wise multiplication using list comprehension
start_time = time.time()
result = [list1[i] * list2[i] for i in range(size)]
end_time = time.time()

# Print time taken
print(f"Time taken for element-wise multiplication using Python lists: {end_time - start_time:.6f} seconds")

Time taken for element-wise multiplication using Python lists: 0.120865 seconds


In [ ]:
size = 1_000_000
array1 = np.random.randint(1, 100, size)
array2 = np.random.randint(1, 100, size)

# Measure time taken for element-wise multiplication using NumPy
start_time = time.time()
result = array1 * array2  # Vectorized multiplication
end_time = time.time()

# Print time taken
print(f"Time taken for element-wise multiplication using NumPy: {end_time - start_time:.6f} seconds")

Time taken for element-wise multiplication using NumPy: 0.004813 seconds


3. Dot Product

In [ ]:
# Generate two lists of size 1,000,000 with random values
size = 1_000_000
list1 = [random.randint(1, 100) for _ in range(size)]
list2 = [random.randint(1, 100) for _ in range(size)]

# Measure time taken for dot product using Python lists
start_time = time.time()
dot_product = sum(list1[i] * list2[i] for i in range(size))  # Manual dot product
end_time = time.time()

# Print time taken
print(f"Dot product using Python lists: {dot_product}")
print(f"Time taken using Python lists: {end_time - start_time:.6f} seconds")

Dot product using Python lists: 2547132217
Time taken using Python lists: 0.097936 seconds


In [ ]:
size = 1_000_000
array1 = np.random.randint(1, 100, size)
array2 = np.random.randint(1, 100, size)

# Measure time taken for dot product using NumPy
start_time = time.time()
dot_product = np.dot(array1, array2)  # Optimized NumPy dot product
end_time = time.time()

# Print time taken
print(f"Dot product using NumPy: {dot_product}")
print(f"Time taken using NumPy: {end_time - start_time:.6f} seconds")

Dot product using NumPy: 2502390292
Time taken using NumPy: 0.001752 seconds


4. Matrix Multiplication

In [ ]:
size = 1000
matrix1 = np.random.randint(1, 10, (size, size))
matrix2 = np.random.randint(1, 10, (size, size))

# Measure time taken for matrix multiplication using NumPy
start_time = time.time()
result = np.dot(matrix1, matrix2)  # Optimized NumPy matrix multiplication
end_time = time.time()

# Print time taken
print(f"Time taken for matrix multiplication using NumPy: {end_time - start_time:.6f} seconds")

Time taken for matrix multiplication using NumPy: 1.838282 seconds


In [ ]:
import time
import random

# Function to perform matrix multiplication for Python lists
def matrix_multiply_python(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):  # Iterate over rows of matrix1
        row = []
        for j in range(len(matrix2[0])):  # Iterate over columns of matrix2
            value = sum(matrix1[i][k] * matrix2[k][j] for k in range(len(matrix2)))
            row.append(value)
        result.append(row)
    return result

# Generate two matrices of size 1000x1000 with random values
size = 1000
matrix1 = [[random.randint(1, 10) for _ in range(size)] for _ in range(size)]
matrix2 = [[random.randint(1, 10) for _ in range(size)] for _ in range(size)]

# Measure time taken for matrix multiplication using Python lists
start_time = time.time()
result = matrix_multiply_python(matrix1, matrix2)
end_time = time.time()

# Print time taken
print(f"Time taken for matrix multiplication using Python lists: {end_time - start_time:.6f} seconds")


Time taken for matrix multiplication using Python lists: 107.163234 seconds
